server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
    expected-client-renewal-interval-seconds: 1
    lease-expiration-duration-in-seconds: 30
    eviction-interval-timer-in-ms: 60
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 15

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

